### ISSUE TITLE
How do we install and access this plug-in in GIMP?

### ISSUE THREAD

**Issue by galaxy-nomad** [theobalasis/gimp-guide-grid#1]
I placed this py script in my plug-in folder but can't figure out how to access it inside GIMP.

**Comment by cyberfunk** [comment]
Nevermind. I tried saving the code using the file link which changed it to an html document. I fixed it by downloading th esaource code instead an ddragging droppin trh epy file to my plug-oins folder. The script now shows up as "Guide Grid" under Image>Guides> menu. Thanks!

**Comment by galaxy-nomad** [comment]
Nevermind. I tried saving the code using the file link which changed it to an html document. I fixed it by downloading the source code instead and dragging the guide_grid.py file to my plug-ins folder. The script now shows up as "Guide Grid" under Image>Guides> menu. Thanks!
